language: php
php:
  - 7.2

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=notes
  matrix:
    - DB=mysql

branches:
  only:
    - master

script:
# do nothing - testing has been moved to drone
  - pwd

matrix:
  fast_finish: true
